package voronoi.mappingpojos;
// Generated 15-abr-2013 14:16:16 by Hibernate Tools 3.2.1.GA



/**
 * Anuncio generated by hbm2java
 */
public class Anuncio  implements java.io.Serializable {


     private int id;
     private int parent;
     private String horario;
     private String nombre;
     private int cliente;
     private String logo;
     private int rating;
     private String shortD;
     private String descripcion;
     private String calle;
     private String numero;
     private String observacion;
     private String interior;
     private String colonia;
     private Integer cp;
     private String ciudad;
     private String estado;
     private String pais;
     private String coordenadas;
     private String telefono;
     private String email;
     private String www;
     private String pagos;
     private int comentarios;
     private String extras;
     private String etiquetas;
     private int aprobado;
     private String notas;

    public Anuncio() {
    }

	
    public Anuncio(int id, int parent, String horario, String nombre, int cliente, String logo, int rating, String shortD, String descripcion, String calle, String numero, String observacion, String interior, String colonia, String ciudad, String estado, String pais, String coordenadas, String telefono, String email, String www, String pagos, int comentarios, String extras, String etiquetas, int aprobado, String notas) {
        this.id = id;
        this.parent = parent;
        this.horario = horario;
        this.nombre = nombre;
        this.cliente = cliente;
        this.logo = logo;
        this.rating = rating;
        this.shortD = shortD;
        this.descripcion = descripcion;
        this.calle = calle;
        this.numero = numero;
        this.observacion = observacion;
        this.interior = interior;
        this.colonia = colonia;
        this.ciudad = ciudad;
        this.estado = estado;
        this.pais = pais;
        this.coordenadas = coordenadas;
        this.telefono = telefono;
        this.email = email;
        this.www = www;
        this.pagos = pagos;
        this.comentarios = comentarios;
        this.extras = extras;
        this.etiquetas = etiquetas;
        this.aprobado = aprobado;
        this.notas = notas;
    }
    public Anuncio(int id, int parent, String horario, String nombre, int cliente, String logo, int rating, String shortD, String descripcion, String calle, String numero, String observacion, String interior, String colonia, Integer cp, String ciudad, String estado, String pais, String coordenadas, String telefono, String email, String www, String pagos, int comentarios, String extras, String etiquetas, int aprobado, String notas) {
       this.id = id;
       this.parent = parent;
       this.horario = horario;
       this.nombre = nombre;
       this.cliente = cliente;
       this.logo = logo;
       this.rating = rating;
       this.shortD = shortD;
       this.descripcion = descripcion;
       this.calle = calle;
       this.numero = numero;
       this.observacion = observacion;
       this.interior = interior;
       this.colonia = colonia;
       this.cp = cp;
       this.ciudad = ciudad;
       this.estado = estado;
       this.pais = pais;
       this.coordenadas = coordenadas;
       this.telefono = telefono;
       this.email = email;
       this.www = www;
       this.pagos = pagos;
       this.comentarios = comentarios;
       this.extras = extras;
       this.etiquetas = etiquetas;
       this.aprobado = aprobado;
       this.notas = notas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getParent() {
        return this.parent;
    }
    
    public void setParent(int parent) {
        this.parent = parent;
    }
    public String getHorario() {
        return this.horario;
    }
    
    public void setHorario(String horario) {
        this.horario = horario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getCliente() {
        return this.cliente;
    }
    
    public void setCliente(int cliente) {
        this.cliente = cliente;
    }
    public String getLogo() {
        return this.logo;
    }
    
    public void setLogo(String logo) {
        this.logo = logo;
    }
    public int getRating() {
        return this.rating;
    }
    
    public void setRating(int rating) {
        this.rating = rating;
    }
    public String getShortD() {
        return this.shortD;
    }
    
    public void setShortD(String shortD) {
        this.shortD = shortD;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public String getInterior() {
        return this.interior;
    }
    
    public void setInterior(String interior) {
        this.interior = interior;
    }
    public String getColonia() {
        return this.colonia;
    }
    
    public void setColonia(String colonia) {
        this.colonia = colonia;
    }
    public Integer getCp() {
        return this.cp;
    }
    
    public void setCp(Integer cp) {
        this.cp = cp;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getCoordenadas() {
        return this.coordenadas;
    }
    
    public void setCoordenadas(String coordenadas) {
        this.coordenadas = coordenadas;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getWww() {
        return this.www;
    }
    
    public void setWww(String www) {
        this.www = www;
    }
    public String getPagos() {
        return this.pagos;
    }
    
    public void setPagos(String pagos) {
        this.pagos = pagos;
    }
    public int getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(int comentarios) {
        this.comentarios = comentarios;
    }
    public String getExtras() {
        return this.extras;
    }
    
    public void setExtras(String extras) {
        this.extras = extras;
    }
    public String getEtiquetas() {
        return this.etiquetas;
    }
    
    public void setEtiquetas(String etiquetas) {
        this.etiquetas = etiquetas;
    }
    public int getAprobado() {
        return this.aprobado;
    }
    
    public void setAprobado(int aprobado) {
        this.aprobado = aprobado;
    }
    public String getNotas() {
        return this.notas;
    }
    
    public void setNotas(String notas) {
        this.notas = notas;
    }




}


