package voronoi.mappingpojos;
// Generated 15-abr-2013 14:16:16 by Hibernate Tools 3.2.1.GA

/**
 * Ciudad generated by Howser
 */
public class Ciudad implements java.io.Serializable {
    
     private int id;
     private int estado;
     private String clave;
     private String nombre;
     private int lada;
     private int frecuente;

    public Ciudad() {
        
    }//constructor vacio

    public Ciudad(int id, int estado, String clave, String nombre, int lada, int frecuente) {
       this.id        = id;
       this.estado    = estado;
       this.clave     = clave;
       this.nombre    = nombre;
       this.lada      = lada;
       this.frecuente = frecuente;
    }//constrcutor de copia
   
    public int  getId() {return this.id;}
    public void setId(int id) {this.id = id;}
    
    public int  getEstado() {return this.estado;}
    public void setEstado(int estado) {this.estado = estado;}
    
    public String  getClave() {return this.clave;}
    public void    setClave(String clave) {this.clave = clave;}
    
    public String  getNombre() {return this.nombre;}
    public void    setNombre(String nombre) {this.nombre = nombre;}
    
    public int  getLada() {return this.lada;}
    public void setLada(int lada) {this.lada = lada;}
    
    public int  getFrecuente() {return this.frecuente;}
    public void setFrecuente(int frecuente) {this.frecuente = frecuente;}
    
   

}//class

