package voronoi.mappingpojos;
// Generated 15-abr-2013 14:16:16 by Hibernate Tools 3.2.1.GA



/**
 * Estados generated by hbm2java
 */
public class Estados  implements java.io.Serializable {


     private int id;
     private int codigo;
     private String estado;
     private String municipio;

    public Estados() {
    }

    public Estados(int id, int codigo, String estado, String municipio) {
       this.id = id;
       this.codigo = codigo;
       this.estado = estado;
       this.municipio = municipio;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }




}


